customhost = "employee.coghw13fheqo.us-east-2.rds.amazonaws.com"
customuser = "mohsen"
custompass = "Test$1234"
customdb = "employeedb"
custombucket = "addemployee19241364"
customregion = "us-east-1"
